Repository AY2021S1-TIC4001-4/tp, pull requests merged in 2020-10, with the labels that each got.

#9 v1.0 Skeleton
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/NusExpenses.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/CommandResult.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/commands/SearchCommand.java
  src/main/java/seedu/duke/commands/TotalCommand.java
  src/main/java/seedu/duke/commands/ViewCommand.java
  src/main/java/seedu/duke/data/ReadOnlyTransaction.java
  src/main/java/seedu/duke/data/Transaction.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/utilities/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#14 branch-Ui
  src/main/java/seedu/duke/NusExpenses.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/CommandResult.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/IncorrectCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/data/Transaction.java
  src/main/java/seedu/duke/utilities/Parser.java
  src/main/java/seedu/duke/utilities/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#17 [Total Command] Final Code for total
  src/main/java/seedu/duke/commands/TotalCommand.java
  src/main/java/seedu/duke/utilities/Parser.java
Labels: priority.High, type.Story

#25 User guide v1
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#35 close #30 Storage branch Load and Save
  src/main/java/seedu/duke/NusExpenses.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/IllegalValueException.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/TransactionListDecoded.java
  src/main/java/seedu/duke/storage/TransactionListEncoded.java
Labels: priority.High, type.Enhancement

#39 Branch category
  src/main/java/seedu/duke/NusExpenses.java
  src/main/java/seedu/duke/commands/AddBudgetCommand.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/commands/ViewCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/data/ReadOnlyTransaction.java
  src/main/java/seedu/duke/data/Transaction.java
  src/main/java/seedu/duke/storage/TransactionListDecoded.java
  src/main/java/seedu/duke/storage/TransactionListEncoded.java
  src/main/java/seedu/duke/utilities/Parser.java
  src/main/java/seedu/duke/utilities/Ui.java
  src/test/java/seedu/duke/commands/SearchCommandTest.java
  src/test/java/seedu/duke/commands/TotalCommandTest.java
  src/test/java/seedu/duke/utilities/ParserTest.java
  src/test/java/seedu/duke/utilities/SetupTransactionData.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story

#41 Update view transaction to view with time period
  src/main/java/seedu/duke/commands/ViewCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/utilities/Parser.java
  src/test/java/seedu/duke/commands/ViewCommandTest.java
  src/test/java/seedu/duke/utilities/ParserTest.java
Labels: priority.Medium

#43 Branch view category filter
  src/main/java/seedu/duke/commands/ViewCommand.java
  src/main/java/seedu/duke/data/Transaction.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/utilities/Parser.java
Labels: priority.High, type.Story

#45 Branch fix update category
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/utilities/Parser.java
Labels: priority.High, type.Bug

#52 Branch add expense reminder
  docs/UserGuide.md
  src/main/java/seedu/duke/NusExpenses.java
  src/main/java/seedu/duke/common/Constants.java
Labels: priority.High
